-- ===========================================================================
-- CX SENTINEL — DATABASE SCHEMA
--
-- This file is the definition of the production database. It was NOT written
-- by hand: it was generated from the live Postgres catalogue on 14 September
-- 2026, so it describes what is actually there rather than what anybody
-- remembers building.
--
-- WHY IT EXISTS
--   Until now no .sql file had ever been committed to this repository, and
--   the migration scripts for the first nineteen build steps no longer
--   existed anywhere. About thirty tables had no definition outside the live
--   Supabase instance. That meant the database could not be rebuilt, a second
--   environment could not be created, and no constraint could be reviewed.
--
-- HOW TO USE IT
--   · To read:    this is the reference. It is ordered and commented.
--   · To rebuild: run it top to bottom on an empty database.
--   · To change:  do NOT edit this file to change the database. Write a new
--                 numbered migration, run that, then regenerate this file.
--
-- Every statement is idempotent (IF NOT EXISTS / DROP IF EXISTS), so running
-- it twice is safe.
--
-- ROW LEVEL SECURITY: enabled on every table, with ZERO policies, and the
-- application connects with the service-role key. That is deliberate — see
-- src/lib/supabase.ts — and it means every access decision is made in
-- application code. There is no second line of defence.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. TRIGGER FUNCTIONS
--
-- !! THE FOUR BODIES BELOW ARE RECONSTRUCTED, NOT EXPORTED. !!
-- The catalogue export captured which triggers exist and what they call, but
-- not the source of the functions themselves. These reconstructions match the
-- observed behaviour and are safe to run, but they are the only part of this
-- file that is not verified against the live database. Replace them with the
-- real bodies from functions-export.sql when you have them.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $$;

CREATE OR REPLACE FUNCTION public.audit_log_is_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'The audit trail cannot be changed or deleted.';
END $$;

CREATE OR REPLACE FUNCTION public.signatures_are_immutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'A signature cannot be changed or deleted once given.';
END $$;

CREATE OR REPLACE FUNCTION public.notifications_are_append_only() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'A notice that has been issued cannot be rewritten or deleted.';
END $$;


-- ---------------------------------------------------------------------------
-- 2. TABLES
--
-- Columns only. Every constraint is added in section 3, so the order of this
-- section does not matter and no table has to exist before another.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.areas (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  name                     text NOT NULL,
  code                     text,
  created_at               timestamp with time zone DEFAULT now(),
  site_id                  uuid
);

CREATE TABLE IF NOT EXISTS public.attachments (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  checklist_item_id        uuid,
  file_name                text NOT NULL,
  file_path                text NOT NULL,
  file_url                 text NOT NULL,
  created_at               timestamp with time zone DEFAULT now(),
  review_status            text,
  review_note              text,
  project_id               uuid,
  ai_model                 text,
  ai_reviewed_at           timestamp with time zone,
  ai_reviewed_by_name      text,
  ai_confidence            text,
  ai_appears_to_be         text,
  ai_matches_filing        text,
  ai_mismatch              text,
  ai_problem               text,
  ai_recommendation        text,
  ai_values                jsonb,
  ai_raw                   text,
  rules_run_at             timestamp with time zone,
  rules_verdict            text,
  rules_findings           jsonb,
  rules_measurements       jsonb,
  rules_citations          jsonb,
  rules_tag_found          boolean
);

CREATE TABLE IF NOT EXISTS public.audit_log (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  actor_email              text,
  actor_name               text,
  actor_role               text,
  action                   text NOT NULL,
  entity                   text NOT NULL,
  entity_id                uuid,
  entity_label             text,
  old_value                text,
  new_value                text,
  comment                  text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.check_templates (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid NOT NULL,
  code                     text,
  title                    text NOT NULL,
  level                    text NOT NULL,
  section                  text,
  answer_type              text,
  guidance                 text,
  created_at               timestamp with time zone DEFAULT now(),
  created_by               text
);

CREATE TABLE IF NOT EXISTS public.checklist_items (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  equipment_id             uuid,
  level                    text NOT NULL,
  item                     text NOT NULL,
  status                   text NOT NULL DEFAULT 'pending'::text,
  notes                    text,
  ai_comment               text,
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  updated_at               timestamp with time zone NOT NULL DEFAULT now(),
  review_state             text DEFAULT 'draft'::text,
  review_comment           text,
  reviewed_at              timestamp with time zone,
  inspection_type          text DEFAULT 'surveillance'::text,
  notified_at              timestamp with time zone,
  subject_type             text,
  subject_id               uuid,
  project_id               uuid,
  point_party              text,
  section_path             text,
  answer_type              text,
  source_ref               text,
  source_line              integer,
  serial_no                text,
  evidence_ref             text,
  links_to                 text,
  template_id              uuid
);

CREATE TABLE IF NOT EXISTS public.components (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  equipment_id             uuid NOT NULL,
  tag_id                   text NOT NULL,
  description              text,
  kind                     text,
  serial_number            text,
  created_at               timestamp with time zone DEFAULT now(),
  project_id               uuid NOT NULL,
  category                 text,
  floor                    text,
  location                 text,
  manufacturer             text,
  model                    text,
  critical                 boolean,
  install_status           text NOT NULL DEFAULT 'not_delivered'::text
);

CREATE TABLE IF NOT EXISTS public.controlled_documents (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  subject_type             text,
  subject_id               uuid,
  doc_number               text NOT NULL,
  title                    text,
  doc_type                 text DEFAULT 'specification'::text,
  discipline               text,
  owner                    text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.document_revisions (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id              uuid,
  rev                      text NOT NULL,
  status                   text DEFAULT 'issued'::text,
  issued_date              date,
  effective_from           date,
  superseded_by            uuid,
  file_name                text,
  file_path                text,
  file_url                 text,
  notes                    text,
  created_at               timestamp with time zone DEFAULT now(),
  extracted_text           text,
  extracted_at             timestamp with time zone,
  page_count               integer,
  word_count               integer,
  source_format            text
);

CREATE TABLE IF NOT EXISTS public.equipment (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid NOT NULL,
  tag_id                   text NOT NULL,
  description              text,
  category                 text,
  manufacturer             text,
  model                    text,
  serial                   text,
  location                 text,
  install_status           text NOT NULL DEFAULT 'not_delivered'::text,
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  updated_at               timestamp with time zone NOT NULL DEFAULT now(),
  system_id                uuid,
  subsystem_id             uuid,
  serial_number            text,
  floor                    text,
  building                 text,
  critical                 boolean,
  type_id                  uuid
);

CREATE TABLE IF NOT EXISTS public.equipment_types (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid NOT NULL,
  type_code                text NOT NULL,
  name                     text,
  category                 text,
  manufacturer             text,
  model                    text,
  rating                   text,
  description              text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.gate_rules (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  gate_id                  uuid,
  rule_kind                text NOT NULL,
  label                    text NOT NULL,
  params                   jsonb DEFAULT '{}'::jsonb,
  category                 text,
  mandatory                boolean DEFAULT true,
  sequence                 integer DEFAULT 0,
  status                   text DEFAULT 'pending'::text,
  evidence                 text,
  confirmed_by             text,
  confirmed_at             timestamp with time zone,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.gates (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  subject_type             text,
  subject_id               uuid,
  gate_key                 text NOT NULL,
  name                     text NOT NULL,
  stage_key                text,
  sequence                 integer DEFAULT 0,
  status                   text DEFAULT 'open'::text,
  planned_for              timestamp with time zone,
  notes                    text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.instruments (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  instrument_id            text NOT NULL,
  name                     text,
  manufacturer             text,
  model                    text,
  serial_number            text,
  cert_number              text,
  calibration_date         date,
  calibration_expiry       date,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.issue_photos (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid NOT NULL,
  issue_id                 uuid NOT NULL,
  kind                     text NOT NULL DEFAULT 'defect'::text,
  file_name                text,
  file_path                text,
  file_url                 text,
  content_type             text,
  size_bytes               bigint,
  caption                  text,
  taken_at                 timestamp with time zone,
  uploaded_by_name         text,
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  ai_model                 text,
  ai_reviewed_at           timestamp with time zone,
  ai_reviewed_by_name      text,
  ai_confidence            text,
  ai_problem               text,
  ai_recommendation        text,
  ai_raw                   text
);

CREATE TABLE IF NOT EXISTS public.issues (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  equipment_id             uuid,
  title                    text NOT NULL,
  description              text,
  severity                 text NOT NULL DEFAULT 'minor'::text,
  status                   text NOT NULL DEFAULT 'open'::text,
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  updated_at               timestamp with time zone NOT NULL DEFAULT now(),
  category                 text,
  checklist_item_id        uuid,
  ai_comment               text,
  subject_type             text,
  subject_id               uuid,
  project_id               uuid,
  level                    text,
  ref                      text,
  raised_by                text,
  responsible_party        text,
  discipline               text,
  location                 text,
  due_date                 date,
  closed_at                timestamp with time zone,
  closed_by                text,
  verified_at              timestamp with time zone,
  verified_by              text,
  ai_model                 text,
  ai_reviewed_at           timestamp with time zone,
  ai_reviewed_by_name      text,
  ai_confidence            text,
  ai_problem               text,
  ai_recommendation        text,
  ai_likely_cause          text,
  ai_verification          text,
  ai_blocks                text,
  ai_kind                  text,
  ai_raw                   text,
  rules_run_at             timestamp with time zone,
  rules_kind               text,
  rules_findings           jsonb,
  rules_citations          jsonb
);

CREATE TABLE IF NOT EXISTS public.itp_conventions (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid NOT NULL,
  level                    text NOT NULL,
  inspection_type          text NOT NULL,
  party                    text NOT NULL,
  note                     text,
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  created_by_name          text
);

CREATE TABLE IF NOT EXISTS public.layout_cables (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  layout_id                uuid,
  project_id               uuid,
  from_local               integer,
  to_local                 integer,
  csa                      numeric,
  runs                     integer,
  circuits                 integer,
  length_m                 numeric,
  local_id                 integer
);

CREATE TABLE IF NOT EXISTS public.layout_items (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  layout_id                uuid,
  project_id               uuid,
  equipment_id             uuid,
  kind                     text,
  label                    text,
  x                        numeric,
  y                        numeric,
  dir                      text,
  kva                      numeric,
  pf                       numeric,
  volts                    numeric,
  local_id                 integer
);

CREATE TABLE IF NOT EXISTS public.layouts (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  project_id               uuid,
  subject_type             text,
  subject_id               uuid,
  name                     text,
  room_w                   numeric,
  room_d                   numeric,
  ambient_c                numeric,
  vd_guidance              text,
  notes                    text,
  revision                 text,
  frozen_at                timestamp with time zone,
  updated_at               timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.lifecycle_stages (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  stage_key                text NOT NULL,
  name                     text NOT NULL,
  sequence                 integer DEFAULT 0,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meetings (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  title                    text NOT NULL,
  meeting_date             date,
  attendees                text,
  notes                    text,
  decisions                text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.milestones (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  name                     text NOT NULL,
  target_date              date,
  status                   text DEFAULT 'planned'::text,
  notes                    text,
  created_at               timestamp with time zone DEFAULT now(),
  checklist_item_id        uuid
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  kind                     text NOT NULL DEFAULT 'inspection_notice'::text,
  entity                   text,
  entity_id                uuid,
  entity_label             text,
  subject                  text,
  body                     text,
  recipients               text,
  recipient_names          text,
  scheduled_for            timestamp with time zone,
  channel                  text DEFAULT 'manual_email'::text,
  status                   text DEFAULT 'composed'::text,
  sent_at                  timestamp with time zone,
  created_by_email         text,
  created_by_name          text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.obligations (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  ref                      text,
  document_id              uuid,
  revision_id              uuid,
  source_name              text,
  clause                   text,
  statement                text NOT NULL,
  party                    text,
  obligation_type          text,
  level                    text,
  stage_key                text,
  status                   text DEFAULT 'open'::text,
  owner                    text,
  due_date                 date,
  evidence                 text,
  notes                    text,
  subject_type             text,
  subject_id               uuid,
  origin                   text DEFAULT 'manual'::text,
  closed_at                timestamp with time zone,
  closed_by                text,
  accepted_at              timestamp with time zone,
  accepted_by              text,
  created_at               timestamp with time zone DEFAULT now(),
  created_by_name          text,
  ai_model                 text,
  ai_reviewed_at           timestamp with time zone,
  ai_reviewed_by_name      text,
  ai_confidence            text,
  ai_discharge             text,
  ai_standing              text,
  ai_risk                  text,
  ai_disagreement          text,
  ai_ask                   text,
  ai_raw                   text
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id                       uuid NOT NULL,
  role                     text NOT NULL DEFAULT 'admin'::text,
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  full_name                text
);

CREATE TABLE IF NOT EXISTS public.project_contacts (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  full_name                text NOT NULL,
  company                  text,
  email                    text,
  phone                    text,
  party                    text DEFAULT 'client'::text,
  job_title                text,
  discipline               text,
  is_witness               boolean DEFAULT true,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.project_files (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  file_name                text NOT NULL,
  file_path                text NOT NULL,
  file_url                 text NOT NULL,
  category                 text,
  description              text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.project_members (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  email                    text NOT NULL,
  full_name                text,
  company                  text,
  role                     text NOT NULL DEFAULT 'engineer'::text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.project_roles (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  role_key                 text NOT NULL,
  label                    text NOT NULL,
  note                     text,
  caps                     text NOT NULL DEFAULT 'view'::text,
  sequence                 integer DEFAULT 0,
  active                   boolean DEFAULT true,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.projects (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  name                     text NOT NULL,
  site_type                text,
  location                 text,
  status                   text NOT NULL DEFAULT 'planning'::text,
  created_at               timestamp with time zone NOT NULL DEFAULT now(),
  updated_at               timestamp with time zone NOT NULL DEFAULT now(),
  client                   text,
  start_date               date,
  target_date              date,
  config                   jsonb
);

CREATE TABLE IF NOT EXISTS public.requirement_verifications (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  requirement_id           uuid,
  activity_kind            text NOT NULL,
  activity_id              uuid NOT NULL,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.requirements (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  ref                      text,
  statement                text NOT NULL,
  subject_type             text,
  subject_id               uuid,
  source_kind              text DEFAULT 'specification'::text,
  document_id              uuid,
  source_revision          text,
  clause                   text,
  verification_method      text DEFAULT 'test'::text,
  criticality              text DEFAULT 'normal'::text,
  acceptance               text,
  notes                    text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.signatures (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  entity                   text NOT NULL,
  entity_id                uuid NOT NULL,
  entity_label             text,
  signer_email             text,
  signer_name              text,
  signer_role              text,
  signer_company           text,
  decision                 text NOT NULL,
  statement                text,
  comment                  text,
  signed_name              text,
  user_agent               text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sites (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  name                     text NOT NULL,
  code                     text,
  location                 text,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.subsystems (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  system_id                uuid,
  code                     text,
  name                     text NOT NULL,
  created_at               timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.systems (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  area_id                  uuid,
  system_id                text NOT NULL,
  name                     text NOT NULL,
  discipline               text,
  description              text,
  boundary                 text,
  responsible              text,
  stage                    text DEFAULT 'construction'::text,
  created_at               timestamp with time zone DEFAULT now(),
  building                 text,
  floor                    text
);

CREATE TABLE IF NOT EXISTS public.tasks (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id               uuid,
  title                    text NOT NULL,
  description              text,
  assignee                 text,
  due_date                 date,
  status                   text DEFAULT 'open'::text,
  priority                 text DEFAULT 'normal'::text,
  created_at               timestamp with time zone DEFAULT now(),
  level                    text
);

CREATE TABLE IF NOT EXISTS public.test_records (
  id                       uuid NOT NULL DEFAULT gen_random_uuid(),
  equipment_id             uuid,
  checklist_item_id        uuid,
  test_ref                 text,
  name                     text NOT NULL,
  procedure_ref            text,
  preconditions            text,
  criteria_type            text DEFAULT 'max'::text,
  expected_min             numeric,
  expected_max             numeric,
  unit                     text,
  criteria_text            text,
  actual_value             numeric,
  actual_text              text,
  result                   text DEFAULT 'pending'::text,
  instrument_id            uuid,
  tested_by                text,
  tested_at                date,
  witness                  text,
  comments                 text,
  approval_state           text DEFAULT 'draft'::text,
  created_at               timestamp with time zone DEFAULT now(),
  inspection_type          text DEFAULT 'surveillance'::text,
  notified_at              timestamp with time zone,
  subject_type             text,
  subject_id               uuid,
  project_id               uuid,
  point_party              text
);


-- ---------------------------------------------------------------------------
-- 3. CONSTRAINTS
--
-- Primary keys first, then unique and check constraints, then foreign keys —
-- so a foreign key never arrives before the key it points at.
-- ---------------------------------------------------------------------------

-- Primary keys
ALTER TABLE public.areas DROP CONSTRAINT IF EXISTS areas_pkey;
ALTER TABLE public.areas ADD CONSTRAINT areas_pkey PRIMARY KEY (id);
ALTER TABLE public.attachments DROP CONSTRAINT IF EXISTS attachments_pkey;
ALTER TABLE public.attachments ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);
ALTER TABLE public.audit_log DROP CONSTRAINT IF EXISTS audit_log_pkey;
ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
ALTER TABLE public.check_templates DROP CONSTRAINT IF EXISTS check_templates_pkey;
ALTER TABLE public.check_templates ADD CONSTRAINT check_templates_pkey PRIMARY KEY (id);
ALTER TABLE public.checklist_items DROP CONSTRAINT IF EXISTS checklist_items_pkey;
ALTER TABLE public.checklist_items ADD CONSTRAINT checklist_items_pkey PRIMARY KEY (id);
ALTER TABLE public.components DROP CONSTRAINT IF EXISTS components_pkey;
ALTER TABLE public.components ADD CONSTRAINT components_pkey PRIMARY KEY (id);
ALTER TABLE public.controlled_documents DROP CONSTRAINT IF EXISTS controlled_documents_pkey;
ALTER TABLE public.controlled_documents ADD CONSTRAINT controlled_documents_pkey PRIMARY KEY (id);
ALTER TABLE public.document_revisions DROP CONSTRAINT IF EXISTS document_revisions_pkey;
ALTER TABLE public.document_revisions ADD CONSTRAINT document_revisions_pkey PRIMARY KEY (id);
ALTER TABLE public.equipment DROP CONSTRAINT IF EXISTS equipment_pkey;
ALTER TABLE public.equipment ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);
ALTER TABLE public.equipment_types DROP CONSTRAINT IF EXISTS equipment_types_pkey;
ALTER TABLE public.equipment_types ADD CONSTRAINT equipment_types_pkey PRIMARY KEY (id);
ALTER TABLE public.gate_rules DROP CONSTRAINT IF EXISTS gate_rules_pkey;
ALTER TABLE public.gate_rules ADD CONSTRAINT gate_rules_pkey PRIMARY KEY (id);
ALTER TABLE public.gates DROP CONSTRAINT IF EXISTS gates_pkey;
ALTER TABLE public.gates ADD CONSTRAINT gates_pkey PRIMARY KEY (id);
ALTER TABLE public.instruments DROP CONSTRAINT IF EXISTS instruments_pkey;
ALTER TABLE public.instruments ADD CONSTRAINT instruments_pkey PRIMARY KEY (id);
ALTER TABLE public.issue_photos DROP CONSTRAINT IF EXISTS issue_photos_pkey;
ALTER TABLE public.issue_photos ADD CONSTRAINT issue_photos_pkey PRIMARY KEY (id);
ALTER TABLE public.issues DROP CONSTRAINT IF EXISTS issues_pkey;
ALTER TABLE public.issues ADD CONSTRAINT issues_pkey PRIMARY KEY (id);
ALTER TABLE public.itp_conventions DROP CONSTRAINT IF EXISTS itp_conventions_pkey;
ALTER TABLE public.itp_conventions ADD CONSTRAINT itp_conventions_pkey PRIMARY KEY (id);
ALTER TABLE public.layout_cables DROP CONSTRAINT IF EXISTS layout_cables_pkey;
ALTER TABLE public.layout_cables ADD CONSTRAINT layout_cables_pkey PRIMARY KEY (id);
ALTER TABLE public.layout_items DROP CONSTRAINT IF EXISTS layout_items_pkey;
ALTER TABLE public.layout_items ADD CONSTRAINT layout_items_pkey PRIMARY KEY (id);
ALTER TABLE public.layouts DROP CONSTRAINT IF EXISTS layouts_pkey;
ALTER TABLE public.layouts ADD CONSTRAINT layouts_pkey PRIMARY KEY (id);
ALTER TABLE public.lifecycle_stages DROP CONSTRAINT IF EXISTS lifecycle_stages_pkey;
ALTER TABLE public.lifecycle_stages ADD CONSTRAINT lifecycle_stages_pkey PRIMARY KEY (id);
ALTER TABLE public.meetings DROP CONSTRAINT IF EXISTS meetings_pkey;
ALTER TABLE public.meetings ADD CONSTRAINT meetings_pkey PRIMARY KEY (id);
ALTER TABLE public.milestones DROP CONSTRAINT IF EXISTS milestones_pkey;
ALTER TABLE public.milestones ADD CONSTRAINT milestones_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_pkey;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.obligations DROP CONSTRAINT IF EXISTS obligations_pkey;
ALTER TABLE public.obligations ADD CONSTRAINT obligations_pkey PRIMARY KEY (id);
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_pkey;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.project_contacts DROP CONSTRAINT IF EXISTS project_contacts_pkey;
ALTER TABLE public.project_contacts ADD CONSTRAINT project_contacts_pkey PRIMARY KEY (id);
ALTER TABLE public.project_files DROP CONSTRAINT IF EXISTS project_files_pkey;
ALTER TABLE public.project_files ADD CONSTRAINT project_files_pkey PRIMARY KEY (id);
ALTER TABLE public.project_members DROP CONSTRAINT IF EXISTS project_members_pkey;
ALTER TABLE public.project_members ADD CONSTRAINT project_members_pkey PRIMARY KEY (id);
ALTER TABLE public.project_roles DROP CONSTRAINT IF EXISTS project_roles_pkey;
ALTER TABLE public.project_roles ADD CONSTRAINT project_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS projects_pkey;
ALTER TABLE public.projects ADD CONSTRAINT projects_pkey PRIMARY KEY (id);
ALTER TABLE public.requirement_verifications DROP CONSTRAINT IF EXISTS requirement_verifications_pkey;
ALTER TABLE public.requirement_verifications ADD CONSTRAINT requirement_verifications_pkey PRIMARY KEY (id);
ALTER TABLE public.requirements DROP CONSTRAINT IF EXISTS requirements_pkey;
ALTER TABLE public.requirements ADD CONSTRAINT requirements_pkey PRIMARY KEY (id);
ALTER TABLE public.signatures DROP CONSTRAINT IF EXISTS signatures_pkey;
ALTER TABLE public.signatures ADD CONSTRAINT signatures_pkey PRIMARY KEY (id);
ALTER TABLE public.sites DROP CONSTRAINT IF EXISTS sites_pkey;
ALTER TABLE public.sites ADD CONSTRAINT sites_pkey PRIMARY KEY (id);
ALTER TABLE public.subsystems DROP CONSTRAINT IF EXISTS subsystems_pkey;
ALTER TABLE public.subsystems ADD CONSTRAINT subsystems_pkey PRIMARY KEY (id);
ALTER TABLE public.systems DROP CONSTRAINT IF EXISTS systems_pkey;
ALTER TABLE public.systems ADD CONSTRAINT systems_pkey PRIMARY KEY (id);
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_pkey;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);
ALTER TABLE public.test_records DROP CONSTRAINT IF EXISTS test_records_pkey;
ALTER TABLE public.test_records ADD CONSTRAINT test_records_pkey PRIMARY KEY (id);

-- Unique constraints

-- Check constraints — the real vocabulary of this application
ALTER TABLE public.checklist_items DROP CONSTRAINT IF EXISTS checklist_items_level_check;
ALTER TABLE public.checklist_items ADD CONSTRAINT checklist_items_level_check CHECK ((level = ANY (ARRAY['L1_fat'::text, 'L2_iv'::text, 'L3_prefunctional'::text, 'L4_fpt'::text, 'L5_ist'::text])));
ALTER TABLE public.checklist_items DROP CONSTRAINT IF EXISTS checklist_items_status_check;
ALTER TABLE public.checklist_items ADD CONSTRAINT checklist_items_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'pass'::text, 'fail'::text, 'na'::text])));
ALTER TABLE public.equipment DROP CONSTRAINT IF EXISTS equipment_category_check;
ALTER TABLE public.equipment ADD CONSTRAINT equipment_category_check CHECK (((category IS NULL) OR (category = ANY (ARRAY['electrical'::text, 'mechanical'::text, 'civil_structural'::text, 'architectural'::text, 'plumbing_public_health'::text, 'elv_security'::text, 'fire_life_safety'::text, 'controls_bms'::text, 'it_whitespace'::text, 'substation_protection'::text]))));
ALTER TABLE public.equipment DROP CONSTRAINT IF EXISTS equipment_install_status_check;
ALTER TABLE public.equipment ADD CONSTRAINT equipment_install_status_check CHECK ((install_status = ANY (ARRAY['not_delivered'::text, 'received'::text, 'installed'::text, 'energized'::text])));
ALTER TABLE public.issues DROP CONSTRAINT IF EXISTS issues_severity_check;
ALTER TABLE public.issues ADD CONSTRAINT issues_severity_check CHECK ((severity = ANY (ARRAY['critical'::text, 'major'::text, 'minor'::text, 'observation'::text])));
ALTER TABLE public.issues DROP CONSTRAINT IF EXISTS issues_status_check;
ALTER TABLE public.issues ADD CONSTRAINT issues_status_check CHECK ((status = ANY (ARRAY['open'::text, 'in_progress'::text, 'ready_for_retest'::text, 'verified'::text, 'closed'::text])));
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'engineer'::text, 'viewer'::text])));
ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS projects_config_is_object;
ALTER TABLE public.projects ADD CONSTRAINT projects_config_is_object CHECK (((config IS NULL) OR (jsonb_typeof(config) = 'object'::text)));
ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS projects_site_type_check;
ALTER TABLE public.projects ADD CONSTRAINT projects_site_type_check CHECK ((site_type = ANY (ARRAY['data_center'::text, 'substation'::text, 'power_plant'::text])));
ALTER TABLE public.projects DROP CONSTRAINT IF EXISTS projects_status_check;
ALTER TABLE public.projects ADD CONSTRAINT projects_status_check CHECK ((status = ANY (ARRAY['planning'::text, 'active'::text, 'on_hold'::text, 'complete'::text])));

-- Foreign keys
ALTER TABLE public.areas DROP CONSTRAINT IF EXISTS areas_project_id_fkey;
ALTER TABLE public.areas ADD CONSTRAINT areas_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.areas DROP CONSTRAINT IF EXISTS areas_site_id_fkey;
ALTER TABLE public.areas ADD CONSTRAINT areas_site_id_fkey FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE SET NULL;
ALTER TABLE public.attachments DROP CONSTRAINT IF EXISTS attachments_checklist_item_id_fkey;
ALTER TABLE public.attachments ADD CONSTRAINT attachments_checklist_item_id_fkey FOREIGN KEY (checklist_item_id) REFERENCES checklist_items(id) ON DELETE CASCADE;
ALTER TABLE public.attachments DROP CONSTRAINT IF EXISTS attachments_project_id_fkey;
ALTER TABLE public.attachments ADD CONSTRAINT attachments_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.check_templates DROP CONSTRAINT IF EXISTS check_templates_project_id_fkey;
ALTER TABLE public.check_templates ADD CONSTRAINT check_templates_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.checklist_items DROP CONSTRAINT IF EXISTS checklist_items_equipment_id_fkey;
ALTER TABLE public.checklist_items ADD CONSTRAINT checklist_items_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE public.checklist_items DROP CONSTRAINT IF EXISTS checklist_items_project_id_fkey;
ALTER TABLE public.checklist_items ADD CONSTRAINT checklist_items_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.components DROP CONSTRAINT IF EXISTS components_equipment_id_fkey;
ALTER TABLE public.components ADD CONSTRAINT components_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE public.components DROP CONSTRAINT IF EXISTS components_project_id_fkey;
ALTER TABLE public.components ADD CONSTRAINT components_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.controlled_documents DROP CONSTRAINT IF EXISTS controlled_documents_project_id_fkey;
ALTER TABLE public.controlled_documents ADD CONSTRAINT controlled_documents_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.document_revisions DROP CONSTRAINT IF EXISTS document_revisions_document_id_fkey;
ALTER TABLE public.document_revisions ADD CONSTRAINT document_revisions_document_id_fkey FOREIGN KEY (document_id) REFERENCES controlled_documents(id) ON DELETE CASCADE;
ALTER TABLE public.document_revisions DROP CONSTRAINT IF EXISTS document_revisions_superseded_by_fkey;
ALTER TABLE public.document_revisions ADD CONSTRAINT document_revisions_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES document_revisions(id) ON DELETE SET NULL;
ALTER TABLE public.equipment DROP CONSTRAINT IF EXISTS equipment_project_id_fkey;
ALTER TABLE public.equipment ADD CONSTRAINT equipment_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.equipment DROP CONSTRAINT IF EXISTS equipment_subsystem_id_fkey;
ALTER TABLE public.equipment ADD CONSTRAINT equipment_subsystem_id_fkey FOREIGN KEY (subsystem_id) REFERENCES subsystems(id) ON DELETE SET NULL;
ALTER TABLE public.equipment DROP CONSTRAINT IF EXISTS equipment_system_id_fkey;
ALTER TABLE public.equipment ADD CONSTRAINT equipment_system_id_fkey FOREIGN KEY (system_id) REFERENCES systems(id) ON DELETE SET NULL;
ALTER TABLE public.equipment DROP CONSTRAINT IF EXISTS equipment_type_id_fkey;
ALTER TABLE public.equipment ADD CONSTRAINT equipment_type_id_fkey FOREIGN KEY (type_id) REFERENCES equipment_types(id) ON DELETE SET NULL;
ALTER TABLE public.equipment_types DROP CONSTRAINT IF EXISTS equipment_types_project_id_fkey;
ALTER TABLE public.equipment_types ADD CONSTRAINT equipment_types_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.gate_rules DROP CONSTRAINT IF EXISTS gate_rules_gate_id_fkey;
ALTER TABLE public.gate_rules ADD CONSTRAINT gate_rules_gate_id_fkey FOREIGN KEY (gate_id) REFERENCES gates(id) ON DELETE CASCADE;
ALTER TABLE public.gates DROP CONSTRAINT IF EXISTS gates_project_id_fkey;
ALTER TABLE public.gates ADD CONSTRAINT gates_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.instruments DROP CONSTRAINT IF EXISTS instruments_project_id_fkey;
ALTER TABLE public.instruments ADD CONSTRAINT instruments_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.issue_photos DROP CONSTRAINT IF EXISTS issue_photos_project_id_fkey;
ALTER TABLE public.issue_photos ADD CONSTRAINT issue_photos_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.issues DROP CONSTRAINT IF EXISTS issues_checklist_item_id_fkey;
ALTER TABLE public.issues ADD CONSTRAINT issues_checklist_item_id_fkey FOREIGN KEY (checklist_item_id) REFERENCES checklist_items(id) ON DELETE SET NULL;
ALTER TABLE public.issues DROP CONSTRAINT IF EXISTS issues_equipment_id_fkey;
ALTER TABLE public.issues ADD CONSTRAINT issues_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE public.issues DROP CONSTRAINT IF EXISTS issues_project_id_fkey;
ALTER TABLE public.issues ADD CONSTRAINT issues_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.itp_conventions DROP CONSTRAINT IF EXISTS itp_conventions_project_id_fkey;
ALTER TABLE public.itp_conventions ADD CONSTRAINT itp_conventions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.layout_cables DROP CONSTRAINT IF EXISTS layout_cables_layout_id_fkey;
ALTER TABLE public.layout_cables ADD CONSTRAINT layout_cables_layout_id_fkey FOREIGN KEY (layout_id) REFERENCES layouts(id) ON DELETE CASCADE;
ALTER TABLE public.layout_cables DROP CONSTRAINT IF EXISTS layout_cables_project_id_fkey;
ALTER TABLE public.layout_cables ADD CONSTRAINT layout_cables_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.layout_items DROP CONSTRAINT IF EXISTS layout_items_equipment_id_fkey;
ALTER TABLE public.layout_items ADD CONSTRAINT layout_items_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE SET NULL;
ALTER TABLE public.layout_items DROP CONSTRAINT IF EXISTS layout_items_layout_id_fkey;
ALTER TABLE public.layout_items ADD CONSTRAINT layout_items_layout_id_fkey FOREIGN KEY (layout_id) REFERENCES layouts(id) ON DELETE CASCADE;
ALTER TABLE public.layout_items DROP CONSTRAINT IF EXISTS layout_items_project_id_fkey;
ALTER TABLE public.layout_items ADD CONSTRAINT layout_items_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.layouts DROP CONSTRAINT IF EXISTS layouts_project_id_fkey;
ALTER TABLE public.layouts ADD CONSTRAINT layouts_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.lifecycle_stages DROP CONSTRAINT IF EXISTS lifecycle_stages_project_id_fkey;
ALTER TABLE public.lifecycle_stages ADD CONSTRAINT lifecycle_stages_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.meetings DROP CONSTRAINT IF EXISTS meetings_project_id_fkey;
ALTER TABLE public.meetings ADD CONSTRAINT meetings_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.milestones DROP CONSTRAINT IF EXISTS milestones_checklist_item_id_fkey;
ALTER TABLE public.milestones ADD CONSTRAINT milestones_checklist_item_id_fkey FOREIGN KEY (checklist_item_id) REFERENCES checklist_items(id) ON DELETE SET NULL;
ALTER TABLE public.milestones DROP CONSTRAINT IF EXISTS milestones_project_id_fkey;
ALTER TABLE public.milestones ADD CONSTRAINT milestones_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_project_id_fkey;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.obligations DROP CONSTRAINT IF EXISTS obligations_document_id_fkey;
ALTER TABLE public.obligations ADD CONSTRAINT obligations_document_id_fkey FOREIGN KEY (document_id) REFERENCES controlled_documents(id) ON DELETE SET NULL;
ALTER TABLE public.obligations DROP CONSTRAINT IF EXISTS obligations_project_id_fkey;
ALTER TABLE public.obligations ADD CONSTRAINT obligations_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.obligations DROP CONSTRAINT IF EXISTS obligations_revision_id_fkey;
ALTER TABLE public.obligations ADD CONSTRAINT obligations_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES document_revisions(id) ON DELETE SET NULL;
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.project_contacts DROP CONSTRAINT IF EXISTS project_contacts_project_id_fkey;
ALTER TABLE public.project_contacts ADD CONSTRAINT project_contacts_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.project_files DROP CONSTRAINT IF EXISTS project_files_project_id_fkey;
ALTER TABLE public.project_files ADD CONSTRAINT project_files_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.project_members DROP CONSTRAINT IF EXISTS project_members_project_id_fkey;
ALTER TABLE public.project_members ADD CONSTRAINT project_members_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.project_roles DROP CONSTRAINT IF EXISTS project_roles_project_id_fkey;
ALTER TABLE public.project_roles ADD CONSTRAINT project_roles_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.requirement_verifications DROP CONSTRAINT IF EXISTS requirement_verifications_requirement_id_fkey;
ALTER TABLE public.requirement_verifications ADD CONSTRAINT requirement_verifications_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES requirements(id) ON DELETE CASCADE;
ALTER TABLE public.requirements DROP CONSTRAINT IF EXISTS requirements_document_id_fkey;
ALTER TABLE public.requirements ADD CONSTRAINT requirements_document_id_fkey FOREIGN KEY (document_id) REFERENCES controlled_documents(id) ON DELETE SET NULL;
ALTER TABLE public.requirements DROP CONSTRAINT IF EXISTS requirements_project_id_fkey;
ALTER TABLE public.requirements ADD CONSTRAINT requirements_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.signatures DROP CONSTRAINT IF EXISTS signatures_project_id_fkey;
ALTER TABLE public.signatures ADD CONSTRAINT signatures_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.sites DROP CONSTRAINT IF EXISTS sites_project_id_fkey;
ALTER TABLE public.sites ADD CONSTRAINT sites_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.subsystems DROP CONSTRAINT IF EXISTS subsystems_system_id_fkey;
ALTER TABLE public.subsystems ADD CONSTRAINT subsystems_system_id_fkey FOREIGN KEY (system_id) REFERENCES systems(id) ON DELETE CASCADE;
ALTER TABLE public.systems DROP CONSTRAINT IF EXISTS systems_area_id_fkey;
ALTER TABLE public.systems ADD CONSTRAINT systems_area_id_fkey FOREIGN KEY (area_id) REFERENCES areas(id) ON DELETE SET NULL;
ALTER TABLE public.systems DROP CONSTRAINT IF EXISTS systems_project_id_fkey;
ALTER TABLE public.systems ADD CONSTRAINT systems_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_project_id_fkey;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
ALTER TABLE public.test_records DROP CONSTRAINT IF EXISTS test_records_checklist_item_id_fkey;
ALTER TABLE public.test_records ADD CONSTRAINT test_records_checklist_item_id_fkey FOREIGN KEY (checklist_item_id) REFERENCES checklist_items(id) ON DELETE SET NULL;
ALTER TABLE public.test_records DROP CONSTRAINT IF EXISTS test_records_equipment_id_fkey;
ALTER TABLE public.test_records ADD CONSTRAINT test_records_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE;
ALTER TABLE public.test_records DROP CONSTRAINT IF EXISTS test_records_instrument_id_fkey;
ALTER TABLE public.test_records ADD CONSTRAINT test_records_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES instruments(id) ON DELETE SET NULL;
ALTER TABLE public.test_records DROP CONSTRAINT IF EXISTS test_records_project_id_fkey;
ALTER TABLE public.test_records ADD CONSTRAINT test_records_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;


-- ---------------------------------------------------------------------------
-- 4. INDEXES
--
-- Indexes that merely back a primary key or unique constraint are not
-- repeated here; Postgres creates those with the constraint in section 3.
-- ---------------------------------------------------------------------------

-- attachments
CREATE INDEX IF NOT EXISTS attachments_ai_reviewed ON public.attachments USING btree (project_id, ai_reviewed_at);
CREATE INDEX IF NOT EXISTS attachments_project_id_idx ON public.attachments USING btree (project_id);
CREATE INDEX IF NOT EXISTS attachments_rules_verdict ON public.attachments USING btree (project_id, rules_verdict);

-- audit_log
CREATE INDEX IF NOT EXISTS audit_log_created_at_idx ON public.audit_log USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS audit_log_project_id_idx ON public.audit_log USING btree (project_id);

-- check_templates
CREATE INDEX IF NOT EXISTS check_templates_project_idx ON public.check_templates USING btree (project_id, level);

-- checklist_items
CREATE INDEX IF NOT EXISTS checklist_items_equipment_id_idx ON public.checklist_items USING btree (equipment_id);
CREATE INDEX IF NOT EXISTS checklist_items_inspection_type_idx ON public.checklist_items USING btree (inspection_type);
CREATE INDEX IF NOT EXISTS checklist_items_point_party ON public.checklist_items USING btree (project_id, point_party);
CREATE INDEX IF NOT EXISTS checklist_items_project_idx ON public.checklist_items USING btree (project_id);
CREATE INDEX IF NOT EXISTS checklist_items_review_state_idx ON public.checklist_items USING btree (review_state);
CREATE INDEX IF NOT EXISTS checklist_items_source_ref_idx ON public.checklist_items USING btree (project_id, subject_id, source_ref);
CREATE INDEX IF NOT EXISTS checklist_items_subject_idx ON public.checklist_items USING btree (subject_type, subject_id);
CREATE INDEX IF NOT EXISTS checklist_items_template_idx ON public.checklist_items USING btree (project_id, template_id);

-- components
CREATE INDEX IF NOT EXISTS components_equipment_id_idx ON public.components USING btree (equipment_id);
CREATE INDEX IF NOT EXISTS components_equipment_idx ON public.components USING btree (equipment_id);
CREATE INDEX IF NOT EXISTS components_project_idx ON public.components USING btree (project_id, tag_id);
CREATE UNIQUE INDEX IF NOT EXISTS components_tag_unique ON public.components USING btree (equipment_id, lower(tag_id));

-- controlled_documents
CREATE INDEX IF NOT EXISTS controlled_documents_number_idx ON public.controlled_documents USING btree (doc_number);
CREATE INDEX IF NOT EXISTS controlled_documents_project_idx ON public.controlled_documents USING btree (project_id);

-- document_revisions
CREATE INDEX IF NOT EXISTS document_revisions_document_idx ON public.document_revisions USING btree (document_id);

-- equipment
CREATE INDEX IF NOT EXISTS equipment_building_idx ON public.equipment USING btree (project_id, building) WHERE (building IS NOT NULL);
CREATE INDEX IF NOT EXISTS equipment_category_idx ON public.equipment USING btree (project_id, category);
CREATE INDEX IF NOT EXISTS equipment_floor_idx ON public.equipment USING btree (project_id, floor) WHERE (floor IS NOT NULL);
CREATE INDEX IF NOT EXISTS equipment_project_id_idx ON public.equipment USING btree (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS equipment_tag_unique_ci ON public.equipment USING btree (project_id, lower(tag_id));
CREATE INDEX IF NOT EXISTS equipment_type_idx ON public.equipment USING btree (project_id, type_id) WHERE (type_id IS NOT NULL);

-- equipment_types
CREATE UNIQUE INDEX IF NOT EXISTS equipment_types_code_unique ON public.equipment_types USING btree (project_id, lower(type_code));
CREATE INDEX IF NOT EXISTS equipment_types_project_idx ON public.equipment_types USING btree (project_id, type_code);

-- gate_rules
CREATE INDEX IF NOT EXISTS gate_rules_gate_idx ON public.gate_rules USING btree (gate_id);

-- gates
CREATE INDEX IF NOT EXISTS gates_project_idx ON public.gates USING btree (project_id);
CREATE INDEX IF NOT EXISTS gates_subject_idx ON public.gates USING btree (subject_type, subject_id);

-- issue_photos
CREATE INDEX IF NOT EXISTS issue_photos_issue ON public.issue_photos USING btree (issue_id);
CREATE INDEX IF NOT EXISTS issue_photos_kind ON public.issue_photos USING btree (project_id, kind);
CREATE INDEX IF NOT EXISTS issue_photos_project ON public.issue_photos USING btree (project_id);

-- issues
CREATE INDEX IF NOT EXISTS issues_ai_reviewed ON public.issues USING btree (project_id, ai_reviewed_at);
CREATE INDEX IF NOT EXISTS issues_checklist_item_id_idx ON public.issues USING btree (checklist_item_id);
CREATE INDEX IF NOT EXISTS issues_due_idx ON public.issues USING btree (project_id, due_date);
CREATE INDEX IF NOT EXISTS issues_level_idx ON public.issues USING btree (project_id, level);
CREATE INDEX IF NOT EXISTS issues_project_id_idx ON public.issues USING btree (project_id);
CREATE INDEX IF NOT EXISTS issues_project_idx ON public.issues USING btree (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS issues_ref_idx ON public.issues USING btree (project_id, ref);
CREATE INDEX IF NOT EXISTS issues_subject_idx ON public.issues USING btree (subject_type, subject_id);

-- itp_conventions
CREATE INDEX IF NOT EXISTS itp_conventions_project ON public.itp_conventions USING btree (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS itp_conventions_unique ON public.itp_conventions USING btree (project_id, level, inspection_type);

-- layout_cables
CREATE INDEX IF NOT EXISTS layout_cables_layout_idx ON public.layout_cables USING btree (layout_id);
CREATE UNIQUE INDEX IF NOT EXISTS layout_cables_local_idx ON public.layout_cables USING btree (layout_id, local_id);
CREATE UNIQUE INDEX IF NOT EXISTS layout_cables_pair_idx ON public.layout_cables USING btree (layout_id, from_local, to_local);
CREATE INDEX IF NOT EXISTS layout_cables_project_idx ON public.layout_cables USING btree (project_id);

-- layout_items
CREATE INDEX IF NOT EXISTS layout_items_equipment_idx ON public.layout_items USING btree (equipment_id);
CREATE INDEX IF NOT EXISTS layout_items_layout_idx ON public.layout_items USING btree (layout_id);
CREATE UNIQUE INDEX IF NOT EXISTS layout_items_local_idx ON public.layout_items USING btree (layout_id, local_id);
CREATE INDEX IF NOT EXISTS layout_items_project_idx ON public.layout_items USING btree (project_id);

-- layouts
CREATE INDEX IF NOT EXISTS layouts_project_idx ON public.layouts USING btree (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS layouts_subject_name_idx ON public.layouts USING btree (project_id, subject_type, subject_id, name);

-- lifecycle_stages
CREATE INDEX IF NOT EXISTS lifecycle_stages_project_idx ON public.lifecycle_stages USING btree (project_id);

-- milestones
CREATE INDEX IF NOT EXISTS milestones_checklist_item_id_idx ON public.milestones USING btree (checklist_item_id);

-- notifications
CREATE INDEX IF NOT EXISTS notifications_entity_idx ON public.notifications USING btree (entity, entity_id);
CREATE INDEX IF NOT EXISTS notifications_project_id_idx ON public.notifications USING btree (project_id);

-- obligations
CREATE INDEX IF NOT EXISTS obligations_ai_reviewed ON public.obligations USING btree (project_id, ai_reviewed_at);
CREATE INDEX IF NOT EXISTS obligations_document_idx ON public.obligations USING btree (document_id);
CREATE INDEX IF NOT EXISTS obligations_due_idx ON public.obligations USING btree (project_id, due_date);
CREATE INDEX IF NOT EXISTS obligations_party_idx ON public.obligations USING btree (project_id, party);
CREATE INDEX IF NOT EXISTS obligations_project_idx ON public.obligations USING btree (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS obligations_ref_idx ON public.obligations USING btree (project_id, ref);
CREATE INDEX IF NOT EXISTS obligations_status_idx ON public.obligations USING btree (project_id, status);
CREATE INDEX IF NOT EXISTS obligations_subject_idx ON public.obligations USING btree (subject_type, subject_id);

-- project_contacts
CREATE INDEX IF NOT EXISTS project_contacts_project_id_idx ON public.project_contacts USING btree (project_id);

-- project_members
CREATE INDEX IF NOT EXISTS project_members_project_id_idx ON public.project_members USING btree (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS project_members_unique_email ON public.project_members USING btree (project_id, lower(email));

-- project_roles
CREATE INDEX IF NOT EXISTS project_roles_project_idx ON public.project_roles USING btree (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS project_roles_unique_key ON public.project_roles USING btree (project_id, lower(role_key));

-- requirement_verifications
CREATE INDEX IF NOT EXISTS requirement_verifications_act_idx ON public.requirement_verifications USING btree (activity_kind, activity_id);
CREATE INDEX IF NOT EXISTS requirement_verifications_req_idx ON public.requirement_verifications USING btree (requirement_id);
CREATE UNIQUE INDEX IF NOT EXISTS requirement_verifications_unique_idx ON public.requirement_verifications USING btree (requirement_id, activity_kind, activity_id);

-- requirements
CREATE INDEX IF NOT EXISTS requirements_document_idx ON public.requirements USING btree (document_id);
CREATE INDEX IF NOT EXISTS requirements_project_idx ON public.requirements USING btree (project_id);
CREATE INDEX IF NOT EXISTS requirements_subject_idx ON public.requirements USING btree (subject_type, subject_id);

-- signatures
CREATE INDEX IF NOT EXISTS signatures_entity_idx ON public.signatures USING btree (entity, entity_id);
CREATE INDEX IF NOT EXISTS signatures_project_id_idx ON public.signatures USING btree (project_id);

-- sites
CREATE INDEX IF NOT EXISTS sites_project_id_idx ON public.sites USING btree (project_id);

-- systems
CREATE INDEX IF NOT EXISTS systems_building_idx ON public.systems USING btree (project_id, building) WHERE (building IS NOT NULL);
CREATE INDEX IF NOT EXISTS systems_floor_idx ON public.systems USING btree (project_id, floor) WHERE (floor IS NOT NULL);

-- tasks
CREATE INDEX IF NOT EXISTS tasks_project_level_idx ON public.tasks USING btree (project_id, level);

-- test_records
CREATE INDEX IF NOT EXISTS test_records_inspection_type_idx ON public.test_records USING btree (inspection_type);
CREATE INDEX IF NOT EXISTS test_records_point_party ON public.test_records USING btree (project_id, point_party);
CREATE INDEX IF NOT EXISTS test_records_project_idx ON public.test_records USING btree (project_id);
CREATE INDEX IF NOT EXISTS test_records_subject_idx ON public.test_records USING btree (subject_type, subject_id);


-- ---------------------------------------------------------------------------
-- 5. TRIGGERS
--
-- Three of these make a record permanent: the audit trail, a signature and an
-- issued notice cannot be rewritten or deleted by anything, including this
-- application. That is the property that makes the record worth signing.
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS audit_log_no_delete ON public.audit_log;
CREATE TRIGGER audit_log_no_delete BEFORE DELETE ON public.audit_log FOR EACH ROW EXECUTE FUNCTION audit_log_is_immutable();
DROP TRIGGER IF EXISTS audit_log_no_update ON public.audit_log;
CREATE TRIGGER audit_log_no_update BEFORE UPDATE ON public.audit_log FOR EACH ROW EXECUTE FUNCTION audit_log_is_immutable();
DROP TRIGGER IF EXISTS checklist_items_set_updated_at ON public.checklist_items;
CREATE TRIGGER checklist_items_set_updated_at BEFORE UPDATE ON public.checklist_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS equipment_set_updated_at ON public.equipment;
CREATE TRIGGER equipment_set_updated_at BEFORE UPDATE ON public.equipment FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS issues_set_updated_at ON public.issues;
CREATE TRIGGER issues_set_updated_at BEFORE UPDATE ON public.issues FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS notifications_no_delete ON public.notifications;
CREATE TRIGGER notifications_no_delete BEFORE DELETE ON public.notifications FOR EACH ROW EXECUTE FUNCTION notifications_are_append_only();
DROP TRIGGER IF EXISTS notifications_no_rewrite ON public.notifications;
CREATE TRIGGER notifications_no_rewrite BEFORE UPDATE ON public.notifications FOR EACH ROW EXECUTE FUNCTION notifications_are_append_only();
DROP TRIGGER IF EXISTS projects_set_updated_at ON public.projects;
CREATE TRIGGER projects_set_updated_at BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS signatures_no_delete ON public.signatures;
CREATE TRIGGER signatures_no_delete BEFORE DELETE ON public.signatures FOR EACH ROW EXECUTE FUNCTION signatures_are_immutable();
DROP TRIGGER IF EXISTS signatures_no_update ON public.signatures;
CREATE TRIGGER signatures_no_update BEFORE UPDATE ON public.signatures FOR EACH ROW EXECUTE FUNCTION signatures_are_immutable();


-- ---------------------------------------------------------------------------
-- 6. ROW LEVEL SECURITY
--
-- On for every table, with no policies defined. Nothing reaches these tables
-- except the server holding SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
-- The browser key can read nothing at all.
-- ---------------------------------------------------------------------------

ALTER TABLE public.areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.check_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checklist_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.controlled_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gate_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.instruments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.issue_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.itp_conventions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.layout_cables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.layout_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.layouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lifecycle_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.obligations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requirement_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subsystems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.test_records ENABLE ROW LEVEL SECURITY;


-- ---------------------------------------------------------------------------
-- 7. END
--
-- 38 tables, generated from the live catalogue. No views, no materialised
-- views, no custom types, no row level security policies exist.
-- ---------------------------------------------------------------------------
